embedding_provider: "google-genai-embeddings"       
embedding_model: "gemini-embedding-exp-03-07"

vector_store: "supabase"         
supabase_table_embeddings: "product_embeddings"

# Number of results to return
top_k: 5

llm:
  provider: "google-genai"
  model: "gemini-2.0-flash"
  temperature: 0.0
