services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # bind your source so edits live‑reload in Vite:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
