# Logistics Agent Configuration
# This file contains all configuration settings for the logistics management system

llm:
  provider: "ollama"
  model: "llama3.2:1b"
  temperature: 0.1
  base_url: "http://localhost:11434"
# Logistics Configuration


logistics:
  # Delay threshold in hours - shipments delayed beyond this are flagged
  delay_threshold_hours: 4
  
  # Preferred carriers (in order of preference)
  preferred_carriers:
    - "aramex"
    - "naqel"
  
  # Default pickup/delivery time windows
  default_pickup_window: "09:00-17:00"
  default_delivery_window: "08:00-18:00"
  
  # Maximum retry attempts for failed operations
  max_retries: 3
  
  # Batch processing limits
  max_batch_size: 50
  batch_timeout: 300  # seconds

# Tracking Configuration
tracking:
  # Regex pattern for tracking number validation
  pattern: "^[A-Z0-9]{8,20}$"
  
  # Auto-tracking intervals (in minutes)
  auto_track_interval: 30
  
  # Status update frequency for active shipments
  status_check_frequency: 15  # minutes

# Carrier-Specific Configuration
carriers:
  aramex:
    name: "Aramex"
    api_base_url: "https://ws.aramex.net/ShippingAPI.V2/"
    supported_services:
      - "express"
      - "standard"
      - "economy"
    default_service: "standard"
    max_weight_kg: 30
    coverage_areas:
      - "riyadh"
      - "jeddah"
      - "dammam"
      - "mecca"
      - "medina"
    business_hours: "08:00-18:00"
    
  naqel:
    name: "Naqel Express"
    api_base_url: "https://api.naqelexpress.com/v1/"
    supported_services:
      - "express"
      - "standard"
      - "overnight"
    default_service: "express"
    max_weight_kg: 25
    coverage_areas:
      - "riyadh"
      - "jeddah"
      - "dammam"
      - "khobar"
      - "tabuk"
    business_hours: "07:00-19:00"

# Regional Configuration
regions:
  middle_east:
    timezone: "Asia/Riyadh"
    currency: "SAR"
    default_language: "en"
    supported_cities:
      - name: "Riyadh"
        code: "RUH"
        coordinates: [24.7136, 46.6753]
      - name: "Jeddah"
        code: "JED"
        coordinates: [21.4858, 39.1925]
      - name: "Dammam"
        code: "DMM"
        coordinates: [26.4207, 50.0888]
      - name: "Mecca"
        code: "MEC"
        coordinates: [21.3891, 39.8579]
      - name: "Medina"
        code: "MED"
        coordinates: [24.5247, 39.5692]

# Agent Configuration
agent:
  # Maximum iterations for agent execution
  max_iterations: 10
  
  # Enable verbose logging
  verbose: true
  
  # Handle parsing errors gracefully
  handle_parsing_errors: true
  
  # Return intermediate steps for debugging
  return_intermediate_steps: true
  
  # Agent response timeout
  response_timeout: 60  # seconds

# Monitoring Configuration
monitoring:
  # Enable real-time status monitoring
  enable_monitoring: true
  
  # Status check intervals
  check_intervals:
    in_transit: 30  # minutes
    delayed: 15     # minutes
    delivered: 60   # minutes
  
  # Alert thresholds
  alerts:
    delay_threshold_hours: 4
    critical_delay_hours: 24
    temperature_threshold: 25  # Celsius for sensitive items
  
  # Webhook configuration
  webhooks:
    enabled: true
    timeout: 10  # seconds
    retry_count: 3
    endpoints:
      - name: "status_updates"
        url: "https://your-domain.com/webhooks/status"
        events: ["status_change", "delay_alert", "delivery_complete"]

# Analytics Configuration
analytics:
  # Enable performance analytics
  enabled: true
  
  # Metrics to track
  metrics:
    - "delivery_time"
    - "success_rate"
    - "delay_frequency"
    - "carrier_performance"
    - "route_efficiency"
  
  # Reporting intervals
  reporting:
    daily_summary: true
    weekly_report: true
    monthly_analysis: true
  
  # Data retention (in days)
  data_retention: 90

# Security Configuration
security:
  # API key rotation interval (in days)
  key_rotation_days: 30
  
  # Rate limiting
  rate_limits:
    requests_per_minute: 100
    requests_per_hour: 1000
    requests_per_day: 10000
  
  # Encryption settings
  encryption:
    algorithm: "AES-256"
    key_length: 256

# Database Configuration (if using database storage)
database:
  # Database type
  type: "postgresql"  # or "mysql", "sqlite"
  
  # Connection settings
  host: "localhost"
  port: 5432
  name: "logistics_db"
  
  # Connection pool settings
  pool:
    min_connections: 5
    max_connections: 20
    timeout: 30

# Logging Configuration
logging:
  # Log level
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log file settings
  file:
    enabled: true
    path: "logs/logistics_agent.log"
    max_size: "10MB"
    backup_count: 5
  
  # Console logging
  console:
    enabled: true
    colored: true

# Performance Configuration
performance:
  # Cache settings
  cache:
    enabled: true
    ttl: 300  # seconds
    max_size: 1000  # number of items
  
  # Connection pooling
  connection_pool:
    enabled: true
    max_connections: 50
    timeout: 30
  
  # Request optimization
  optimization:
    batch_requests: true
    compress_responses: true
    use_connection_pooling: true

# Feature Flags
features:
  # Enable/disable specific features
  auto_rerouting: true
  predictive_analytics: true
  real_time_tracking: true
  multi_carrier_optimization: true
  route_optimization: true
  cost_optimization: true
  sustainability_metrics: false  # Future feature

# Notification Configuration
notifications:
  # Email notifications
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "logistics@yourcompany.com"
  
  # SMS notifications
  sms:
    enabled: false
    provider: "twilio"  # or "aws_sns"
  
  # Push notifications
  push:
    enabled: false
    provider: "firebase"
  
  # Notification triggers
  triggers:
    - "shipment_delayed"
    - "delivery_complete"
    - "pickup_scheduled"
    - "route_optimized"

# Integration Configuration
integrations:
  # ERP systems
  erp:
    enabled: false
    system: "sap"  # or "oracle", "custom"
  
  # WMS (Warehouse Management System)
  wms:
    enabled: false
    system: "manhattan"  # or "custom"
  
  # External APIs
  external_apis:
    weather_service: "openweathermap"
    maps_service: "google_maps"
    traffic_service: "google_traffic"

# Development/Testing Configuration
development:
  # Enable debug mode
  debug: false
  
  # Mock external services for testing
  mock_services: false
  
  # Test data configuration
  test_data:
    use_sample_data: false
    sample_shipments: 100
  
  # Development server settings
  dev_server:
    host: "localhost"
    port: 8000
    reload: true