# File: src/agents/InventoryAgent/config.yaml

# 1) LLM settings
llm:
  provider: "google-genai"       # or "openai" if you switch providers later
  model: "gemini-2.0-flash"
  temperature: 0.0

# 2) Use Supabase or in-memory fallback
use_supabase: false

# 3) SKU regex (optional; defaulting to uppercase + digits + dashes)
sku_pattern: "^[A-Z0-9\\-]{5,}$"
