# OrderAgent Configuration
# Handles order creation, status checking, and order management

llm:
  provider: "google-genai"
  model: "gemini-2.0-flash"
  temperature: 0.1

# Agent execution settings
max_iterations: 3

# Order-specific settings
order_settings:
  max_items_per_order: 50
  default_currency: "USD"
  
# Business rules
business_rules:
  minimum_order_value: 10.00
  maximum_order_value: 10000.00
  
# Supabase integration
use_supabase: true